const level1 = new Level (
	[
		new BackgroundImg('../img/3. Background/Layers/5. Water/D.png', 0),
		new BackgroundImg('../img/3. Background/Layers/5. Water/D.png', 2000),
		new BackgroundImg('../img/3. Background/Layers/5. Water/D.png', 4000),
		new BackgroundImg('../img/3. Background/Layers/5. Water/D.png', 6000),
		new BackgroundImg('../img/3. Background/Layers/5. Water/D.png', 8000),

		new BackgroundImg('../img/3. Background/Layers/4.Fondo 2/D.png', 0),
		new BackgroundImg('../img/3. Background/Layers/4.Fondo 2/D.png', 2000),
		new BackgroundImg('../img/3. Background/Layers/4.Fondo 2/D.png', 4000),
		new BackgroundImg('../img/3. Background/Layers/4.Fondo 2/D.png', 6000),
		new BackgroundImg('../img/3. Background/Layers/4.Fondo 2/D.png', 8000),

		new BackgroundImg('../img/3. Background/Layers/3.Fondo 1/D.png', 0),
		new BackgroundImg('../img/3. Background/Layers/3.Fondo 1/D.png', 2000),
		new BackgroundImg('../img/3. Background/Layers/3.Fondo 1/D.png', 4000),
		new BackgroundImg('../img/3. Background/Layers/3.Fondo 1/D.png', 6000),
		new BackgroundImg('../img/3. Background/Layers/3.Fondo 1/D.png', 8000),

		new BackgroundImg('../img/3. Background/Layers/2. Floor/D.png', 0),
		new BackgroundImg('../img/3. Background/Layers/2. Floor/D.png', 2000),
		new BackgroundImg('../img/3. Background/Layers/2. Floor/D.png', 4000),
		new BackgroundImg('../img/3. Background/Layers/2. Floor/D.png', 6000),
		new BackgroundImg('../img/3. Background/Layers/2. Floor/D.png', 8000),
	],
	[
		new RedPufferFish(),
		new GreenPufferFish(),
		new OrangePufferFish(),
		new GreenPufferFish(),
		new GreenJellyFish(),
		new RedPufferFish(),
		new GreenPufferFish(),
		new OrangePufferFish(),
		new GreenPufferFish(),
		new GreenJellyFish(),
		new LilaJellyFish(),
		new RedPufferFish(),
		new YellowJellyFish(),
		new OrangePufferFish(),
		new PinkJellyFish(),
		new RedPufferFish(),
		new GreenPufferFish(),
		new OrangePufferFish(),
		new GreenPufferFish(),
		new GreenJellyFish(),
		new LilaJellyFish(),
		new RedPufferFish(),
		new YellowJellyFish(),
		new OrangePufferFish(),
		new PinkJellyFish(),
		new LilaJellyFish(),
		new RedPufferFish(),
		new YellowJellyFish(),
		new OrangePufferFish(),
		new PinkJellyFish(),
	],[
		new Floor(),
		new Floor(),
		new Floor(),
		new Floor(),
		new Floor(),
	],[
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
	],[
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
	],

)