const level1 = new Level (
	[
		new BackgroundImg('../img/3. Background/Layers/5. Water/D.png', 0),
		new BackgroundImg('../img/3. Background/Layers/5. Water/D.png', 2000),
		new BackgroundImg('../img/3. Background/Layers/5. Water/D.png', 4000),
		new BackgroundImg('../img/3. Background/Layers/4.Fondo 2/D.png', 0),
		new BackgroundImg('../img/3. Background/Layers/4.Fondo 2/D.png', 2000),
		new BackgroundImg('../img/3. Background/Layers/4.Fondo 2/D.png', 4000),
		new BackgroundImg('../img/3. Background/Layers/3.Fondo 1/D.png', 0),
		new BackgroundImg('../img/3. Background/Layers/3.Fondo 1/D.png', 2000),
		new BackgroundImg('../img/3. Background/Layers/3.Fondo 1/D.png', 4000),
		new BackgroundImg('../img/3. Background/Layers/2. Floor/D.png', 0),
		new BackgroundImg('../img/3. Background/Layers/2. Floor/D.png', 2000),
		new BackgroundImg('../img/3. Background/Layers/2. Floor/D.png', 4000),
	],
	[
		new RedPufferFish(),
		new GreenJellyFish(),
		new GreenPufferFish(),
		new YellowJellyFish(),
		new OrangePufferFish(),
		new PinkJellyFish(),
		new LilaJellyFish(),
		new GreenJellyFish(),
		new GreenPufferFish(),
		new LilaJellyFish(),
		new RedPufferFish(),
	],[
		new Floor(),
		new Floor(),
		new Floor(),
		new Floor(),
		new Floor(),
	],[
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
		new Coins(),
	],[
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
		new Poison(),
	],

)